title: Arakoo.com
description: Tasty Java
#theme: just-the-docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arakoo.com/" # the base hostname & protocol for your site, e.g. http://example.com



aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Footer content
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022- Arakoo. <a href=\"https://www.arakoo.com/\">This site is powered by Github Pages.</a>"


